---

- name: Ensure kill machines
  ansible.builtin.command:
    cmd: docker-machine kill `docker-machine ls -f '{{ '{{' }}.Name{{ '}}' }}'`

- name: Ensure remove machines
  ansible.builtin.shell:
    cmd: yes | docker-machine rm `docker-machine ls -f {{ '{{' }}.Name{{ '}}' }}` || true

...