---

- name: Ensure GitLab runner repository
  ansible.builtin.shell:
    cmd:     curl https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

- name: Ensure install Gitlab runner     
  ansible.builtin.apt:
    name: gitlab-runner  
  environment:
    GITLAB_RUNNER_DISABLE_SKEL: 'true'

- name: Ensure install docker-machine
  ansible.builtin.shell:
    cmd: |
      curl -L https://github.com/docker/machine/releases/download/v0.16.2/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
      chmod +x /tmp/docker-machine &&
      sudo cp /tmp/docker-machine /usr/local/bin/docker-machine
    creates: /usr/local/bin/docker-machine

- name: Ensure install docker-machine-driver-hetzner
  ansible.builtin.unarchive:
    remote_src: yes
    src:        https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/{{ gitlab_runner_autoscaling_docker_machine_driver_hetzner_version }}/docker-machine-driver-hetzner_{{ gitlab_runner_autoscaling_docker_machine_driver_hetzner_version }}_linux_amd64.tar.gz
    dest:       /usr/local/bin
    owner:      root
    group:      root
    mode:       +x,go-w

# - name: Ensure S3 Cache
#   community.docker.docker_container:
#     name:                       minio
#     image:                      minio/minio:latest
#     ports:
#       - 9000:9000
#     volumes:
#       - 
#     restart_policy:             always
#     container_default_behavior: compatibility


- name: Ensure register gitlab-runner
  ansible.builtin.shell: 
    cmd: gitlab-runner register --name {{ gitlab_runner_name }} {{ gitlab_runner_autoscaling_args | join(' ') }}
          && touch ansible-shell-done-gitlab-runner-register
          && rm -f ansible-shell-done-gitlab-runner-unregister
  args:
    creates: ansible-shell-done-gitlab-runner-register
  when: not gitlab_runner_unregister

- name: Ensure unregister gitlab-runner
  ansible.builtin.shell: 
    cmd: gitlab-runner unregister --name {{ gitlab_runner_name }}
          && touch ansible-shell-done-gitlab-runner-unregister
          && rm -f ansible-shell-done-gitlab-runner-register
  args:
    creates: ansible-shell-done-gitlab-runner-unregister
  when: gitlab_runner_unregister

...