---

- name: Ensure software-properties-common is installed
  ansible.builtin.apt:
    name: software-properties-common

- name: Ensure python is installed
  ansible.builtin.apt:
    name: python3

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip

- name: Ensure Python library docker
  ansible.builtin.pip:
    name: docker
  
- name: Ensure minio
  community.docker.docker_container:
    name:    minio
    image:   minio/minio:latest
    command: server /export
    ports:
      - "{{ gitlab_runner_autoscaling_minio_port }}:9000"
    volumes:
      - "{{ gitlab_runner_autoscaling_minio_volume }}:/export"
    env:
      MINIO_ROOT_USER:     "{{ gitlab_runner_autoscaling_minio_root_user }}"
      MINIO_ROOT_PASSWORD: "{{ gitlab_runner_autoscaling_minio_root_password }}"
    restart_policy:             always
    container_default_behavior: compatibility

...