---
- name: Ensure clean up gitlab-runner
  ansible.builtin.include_tasks: cleanup.yml

- name: Ensure unregister gitlab-runner
  ansible.builtin.shell:
    cmd: gitlab-runner unregister --name {{ gitlab_runner_autoscaling_name }}
          && touch ansible-shell-done-gitlab-runner-unregister
          && rm -f ansible-shell-done-gitlab-runner-register
  args:
    creates: ansible-shell-done-gitlab-runner-unregister
  failed_when: False

- name: Ensure remove /etc/gitlab-runner/config.toml
  ansible.builtin.file:
    dest:  /etc/gitlab-runner/config.toml
    state: absent
  failed_when: False

...